export const STATIC_CATEGORIES = [
    { _id: "cat_bedroom", name: "Bedroom", visible: true },
    { _id: "cat_bathroom", name: "Bathroom", visible: true },
    { _id: "cat_kitchen", name: "Kitchen", visible: true },
    { _id: "cat_office", name: "Office", visible: true },
    { _id: "cat_living", name: "Living Room", visible: true },
    { _id: "cat_other", name: "Other", visible: true },
    { _id: "cat_structural", name: "Structural", visible: true },
    { _id: "cat_wall", name: "Wall", visible: false }
];

export const STATIC_FURNITURE = [
    { _id: "fur_1", name: "Double bed", width: 1.6, height: 2.0, imagePath: "king-size-bed", category: "cat_bedroom" },
    { _id: "fur_2", name: "Single bed", width: 1, height: 2.0, imagePath: "twin-size-bed", category: "cat_bedroom" },
    { _id: "fur_3", name: "Bedside table 1", width: 0.8, height: 0.5, imagePath: "bedside-table", category: "cat_bedroom" },
    { _id: "fur_4", name: "Bedside table 2", width: 0.8, height: 0.5, imagePath: "noptiera", category: "cat_bedroom" },
    { _id: "fur_5", name: "Bedside rug", width: 0.8, height: 1.2, imagePath: "bedside-rug", category: "cat_bedroom" },
    { _id: "fur_6", name: "Wardrobe - small", width: 1.5, height: 1.0, imagePath: "drawer", category: "cat_bedroom" },
    { _id: "fur_7", name: "Wardrobe - large", width: 2.5, height: 0.8, imagePath: "wardrobe-large", category: "cat_bedroom" },
    { _id: "fur_8", name: "Large plant", width: 1, height: 1, imagePath: "large-plant", category: "cat_bedroom" },
    { _id: "fur_9", name: "Lounge chair", width: 0.8, height: 0.9, imagePath: "lounge-chair", category: "cat_bedroom" },
    { _id: "fur_10", name: "Chair", width: 0.6, height: 0.6, imagePath: "chair-1", category: "cat_bedroom" },
    { _id: "fur_11", name: "Oval rug", width: 1.5, height: 1, imagePath: "round-rug", category: "cat_bedroom" },
    { _id: "fur_12", name: "Table", width: 1.2, height: 0.8, imagePath: "table", category: "cat_bedroom" },
    { _id: "fur_13", name: "Round table - Small", width: 0.6, height: 0.6, imagePath: "round-table", category: "cat_bedroom" },
    
    { _id: "fur_14", name: "Stove - 4 spots", width: 0.6, height: 0.6, imagePath: "stove", category: "cat_kitchen" },
    { _id: "fur_15", name: "Stove - 5 spots", width: 0.8, height: 0.6, imagePath: "5-spot-hob", category: "cat_kitchen" },
    { _id: "fur_16", name: "Fridge", width: 0.6, height: 0.6, imagePath: "kitchenFridge", category: "cat_kitchen" },
    { _id: "fur_17", name: "Sink", width: 1.0, height: 0.6, imagePath: "kitchenSink", category: "cat_kitchen" },
    { _id: "fur_18", name: "Bar counter", width: 1.6, height: 0.6, imagePath: "bar-counter", category: "cat_kitchen" },
    { _id: "fur_19", name: "Bar stool", width: 0.55, height: 0.5, imagePath: "bar-stool", category: "cat_kitchen" },
    { _id: "fur_20", name: "Fume hood", width: 0.6, height: 0.4, imagePath: "fume-hood-md", category: "cat_kitchen" },
    { _id: "fur_21", name: "Double kitchen sink", width: 1.2, height: 0.6, imagePath: "double-sink", category: "cat_kitchen" },
    { _id: "fur_22", name: "Kitchen sink - corner", width: 1.0, height: 0.55, imagePath: "kitchen-sink-corner", category: "cat_kitchen" },
    { _id: "fur_23", name: "Countertop - corner", width: 0.9, height: 0.9, imagePath: "countertop-corner", category: "cat_kitchen" },
    { _id: "fur_24", name: "Table - small", width: 1.2, height: 0.8, imagePath: "table", category: "cat_kitchen" },
    { _id: "fur_25", name: "Plate", width: 0.25, height: 0.2, imagePath: "farfurie furculita", category: "cat_kitchen" },
    { _id: "fur_26", name: "Dishwasher", width: 0.7, height: 0.7, imagePath: "dishwasher", category: "cat_kitchen" },
    { _id: "fur_27", name: "Countertop", width: 0.63, height: 0.63, imagePath: "table", category: "cat_kitchen" },
    { _id: "fur_28", name: "Dinner table - 4 people", width: 1, height: 1, imagePath: "dining-table-square", category: "cat_kitchen" },
    { _id: "fur_29", name: "Dinner table - 6 people", width: 1.6, height: 0.9, imagePath: "dining-table-6", category: "cat_kitchen" },
    { _id: "fur_30", name: "Dinner chair - variant 1", width: 0.7, height: 0.7, imagePath: "chair-2", category: "cat_kitchen" },
    { _id: "fur_31", name: "Dinner chair - variant 2", width: 0.6, height: 0.85, imagePath: "chair-3", category: "cat_kitchen" },

    { _id: "fur_32", name: "Armchair", width: 1.2, height: 1.0, imagePath: "armchair", category: "cat_living" },
    { _id: "fur_33", name: "Couch - 2 seats", width: 1.8, height: 1.0, imagePath: "loveseat", category: "cat_living" },
    { _id: "fur_34", name: "Couch", width: 2.4, height: 1.0, imagePath: "couch", category: "cat_living" },
    { _id: "fur_35", name: "Plant 1", width: 0.6, height: 0.6, imagePath: "plant", category: "cat_living" },
    { _id: "fur_36", name: "Plant 2", width: 0.6, height: 0.6, imagePath: "potted-plant-2", category: "cat_living" },
    { _id: "fur_37", name: "Plant 3", width: 0.6, height: 0.6, imagePath: "potted-plant-1", category: "cat_living" },
    { _id: "fur_38", name: "Sectional couch - front seat", width: 0.7, height: 0.7, imagePath: "sectional-couch-seat", category: "cat_living" },
    { _id: "fur_39", name: "Sectional couch - corner seat", width: 0.7, height: 0.7, imagePath: "sectional-couch-corner-seat", category: "cat_living" },
    { _id: "fur_40", name: "TV", width: 1.1, height: 0.15, imagePath: "televizor", category: "cat_living" },

    { _id: "fur_41", name: "Shoe rack", width: 1.1, height: 0.4, imagePath: "pantofar", category: "cat_other" },
    { _id: "fur_42", name: "Welcome mat", width: 0.6, height: 0.3, imagePath: "welcome", category: "cat_other" },
    { _id: "fur_43", name: "Generic object", width: 0.5, height: 0.5, imagePath: "generic-object", category: "cat_other" },
    { _id: "fur_44", name: "Car", width: 4, height: 2, imagePath: "car", category: "cat_other" },

    { _id: "fur_45", name: "Bathtub", width: 1.0, height: 2.0, imagePath: "bathtub", category: "cat_bathroom" },
    { _id: "fur_46", name: "Bathtub - corner", width: 2.0, height: 2.0, imagePath: "bathtub-corner", category: "cat_bathroom" },
    { _id: "fur_47", name: "Bathtub - oval", width: 1.2, height: 2.0, imagePath: "bathtub-oval", category: "cat_bathroom" },
    { _id: "fur_48", name: "Sink", width: 0.8, height: 0.6, imagePath: "bathroomSink", category: "cat_bathroom" },
    { _id: "fur_49", name: "Corner sink", width: 0.7, height: 0.7, imagePath: "corner-sink", category: "cat_bathroom" },
    { _id: "fur_50", name: "Round sink", width: 0.7, height: 0.7, imagePath: "round-sink", category: "cat_bathroom" },
    { _id: "fur_51", name: "Toilet", width: 0.7, height: 1.0, imagePath: "toilet", category: "cat_bathroom" },
    { _id: "fur_52", name: "Bidet", width: 0.6, height: 0.8, imagePath: "bidet", category: "cat_bathroom" },
    { _id: "fur_53", name: "Shower", width: 1.1, height: 1.1, imagePath: "shower", category: "cat_bathroom" },
    { _id: "fur_54", name: "Washing Machine", width: 0.7, height: 0.7, imagePath: "washing-machine", category: "cat_bathroom" },

    { _id: "fur_55", name: "Chair", width: 0.6, height: 0.6, imagePath: "chair-1", category: "cat_office" },
    { _id: "fur_56", name: "Computer monitor", width: 0.8, height: 0.1, imagePath: "computer-monitor", category: "cat_office" },
    { _id: "fur_57", name: "Computer", width: 0.8, height: 0.4, imagePath: "computer", category: "cat_office" },
    { _id: "fur_58", name: "Corner desk", width: 1, height: 1.5, imagePath: "corner-desk", category: "cat_office" },
    { _id: "fur_59", name: "Desk", width: 1.2, height: 0.8, imagePath: "table", category: "cat_office" },

    { _id: "fur_60", name: "Staircase - small", width: 2.0, height: 1.6, imagePath: "stairs-small-sq", category: "cat_structural" },
    { _id: "fur_61", name: "Staircase - medium", width: 2.0, height: 2.0, imagePath: "stairs-md-sq", category: "cat_structural" },
    { _id: "fur_62", name: "Staircase - long", width: 2.0, height: 4.0, imagePath: "stairs-lg-sq", category: "cat_structural" },
    { _id: "fur_63", name: "Staircase - corner", width: 3.0, height: 3.0, imagePath: "stairs-corner", category: "cat_structural" },
    { _id: "fur_64", name: "Staircase - round", width: 3.0, height: 3.0, imagePath: "stairs-round", category: "cat_structural" },
    { _id: "fur_65", name: "Stair cover", width: 1.0, height: 1.5, imagePath: "stair-cover", category: "cat_structural" },

    { _id: "fur_66", name: "Window", width: 1, height: 0.15, imagePath: "window", category: "cat_wall" },
    { _id: "fur_67", name: "Door", width: 1, height: 1, imagePath: "door", category: "cat_wall" }
];
